
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/molecules/Header/Header";
import { ClerkProvider } from "@clerk/nextjs";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>

    <html lang="en">
      <body className={inter.className + " dark:bg-slate-800 dark:text-white"}>
        <Header/>
        
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
